name: Docker build and push multi-stage

on:
  push:
    branches:
      - "main"
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3.3.2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: 01-task-microservices
          file: 01-task-microservices/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false
          tags: ghcr.io/youssef-harby/advanced-devops-masterclass:${{ github.ref == 'refs/heads/main' && 'latest' || github.ref_name }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: advanced-devops-masterclass
          path: /tmp/advanced-devops-masterclass.tar

  push:
    needs: build
    runs-on: ubuntu-22.04

    env:
      DOCKER_TAG: latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: advanced-devops-masterclass
          path: /tmp

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Docker layers
        uses: actions/cache@v3.3.2
        with:
          path: /tmp/.buildx-cache-new
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Extract tag name if exists
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            DOCKER_TAG=$(echo ${GITHUB_REF#refs/tags/})
            echo "DOCKER_TAG=${DOCKER_TAG}" >> $GITHUB_ENV
            echo "Current Tag inside if: ${DOCKER_TAG}"
          fi
          echo Current Tag is :  ${{ env.DOCKER_TAG }} 🐳

      - name: Push Docker image
        uses: docker/build-push-action@v5
        with:
          load: true
          cache-from: type=local,src=/tmp/.buildx-cache-new
          #   context: 01-task-microservices
          #   file: 01-task-microservices/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/youssef-harby/advanced-devops-masterclass:${{ github.ref == 'refs/heads/main' && 'latest' || github.ref_name }}
