version: '3'
services:
  app1:
    build: .
    container_name: app1
    command: ["poetry", "run", "start"]
    image: yharby/devops-microservices-task1:0.1.0
    ports:
      - '8000:8000'
    restart: always
    volumes:
      - db-data:/app
volumes:
  db-data:
